In [ ]:
# Q1
val = input('How old are you?\n')
age = int(val)
if age > 17 and age < 31 :
  print('Young')
elif age > 30 and age < 66 :
  print('Adult')
else :
  print('In pension')

How old are you?
199
In pension

In [ ]:
# Q2
val = input('What is your salary?\n')
amount = int(val)
tax = 0
if amount > 5000 :
  tax = tax + 5000 * 0.1
  print('salary is above 5000, adding 500 for the first 5000')
  amount = amount - 5000
  if amount > 3000 :
    tax = tax + 3000 * 0.15
    print('salary is above 8000, adding 450')
    amount = amount - 3000
    if amount > 4000 :
      tax = tax + 4000 * 0.22
      print('salary is above 12000, adding 880')
      amount = amount - 4000
      if amount > 8000 :
        tax = tax + 8000 * 0.3
        print('salary is above 20000, adding 2400')
        amount = amount - 8000
        step = amount * 0.5
        tax = tax + step
        print('Adding that rest. that is', step)
      else :
        step = amount * 0.3
        tax = tax + step
        print('salary is less than 20000, adding', step)
    else :
      step = amount * 0.22
      tax = tax + step
      print('salary is less than 12000, adding', step)
  else :
    step = amount * 0.15
    tax = tax + step
    print('salary is less than 8000, adding', step)
else :
  tax = tax + amount * 0.1
  print('salary is less than 5000, adding', tax)

print('Total tax', tax)

What is your salary?
90000
salary is above 5000, adding 500 for the first 5000
salary is above 8000, adding 450
salary is above 12000, adding 880
salary is above 20000, adding 2400
Adding that rest. that is 35000.0
Total tax 39230.0

In [4]:
# Q3
score = 70
result = 10 if score >=60 else 5
print(result)

10

In [1]:
# Q4

a = 30
b = 10
c = 20

max_value =  (a if a > c else c) if a > b else (b if b > c else c)
print(max_value)

30